
import PDFDocument from "pdfkit";
import Appointment from "../models/Appointment.js";
import Payment from "../models/Payment.js";

/* ===========================
   WEEKLY REPORT
=========================== */

export const generateWeeklyReport = async (req, res) => {
  try {
    const { start, end } = req.query;

    if (!start || !end) {
      return res.status(400).json({ error: "Start and End date required" });
    }

    const appointments = await Appointment.find({
      date: { $gte: start, $lte: end }
    });

    const payments = await Payment.find({
      date: { $gte: start, $lte: end }
    });

    const doc = new PDFDocument({
  margin: 50,
  userPassword: process.env.PDF_USER_PASSWORD,
  ownerPassword: process.env.PDF_OWNER_PASSWORD,
  permissions: {
    printing: "highResolution",
    modifying: false,
    copying: false
  }
});

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=Weekly_Report_${start}_to_${end}.pdf`
    );

    doc.pipe(res);

    doc.fontSize(22).text("VS UNISEX SALON", { align: "center" });
    doc.moveDown();

    doc.fontSize(16).text("Weekly Business Report", { align: "center" });
    doc.moveDown();

    doc.text(`Report Duration: ${start} → ${end}`, { align: "center" });
    doc.moveDown(2);

    /* Appointments */

    doc.fontSize(16).text("Appointments", { underline: true });

    appointments.forEach((a, i) => {
      doc
        .fontSize(12)
        .text(`${i + 1}. ${a.service} | ${a.time} | ${a.stylist} | ${a.date}`);
    });

    doc.moveDown();

    /* Payments */

    doc.fontSize(16).text("Payments", { underline: true });

    let total = 0;
    let cash = 0;
    let upi = 0;

    payments.forEach((p, i) => {
      doc.text(`${i + 1}. ${p.method} - ₹${p.amount} - ${p.date}`);

      total += Number(p.amount);

      if (p.method === "Cash") cash += Number(p.amount);
      if (p.method === "UPI") upi += Number(p.amount);
    });

    doc.moveDown();

    doc.fontSize(16).text("Summary", { underline: true });

    doc.text(`Total Cash : ₹${cash}`);
    doc.text(`Total UPI : ₹${upi}`);
    doc.text(`Total Weekly Income : ₹${total}`);

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("gray")
      .text("Generated by VS Salon Management System", {
        align: "center"
      });

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Weekly PDF failed" });
  }
};

/* ===========================
   MONTHLY REPORT
=========================== */

export const generateMonthlyReport = async (req, res) => {
  try {
    const { month } = req.query;

    if (!month) {
      return res.status(400).json({ error: "Month required (YYYY-MM)" });
    }

    const start = `${month}-01`;
    const end = `${month}-31`;

    const appointments = await Appointment.find({
      date: { $gte: start, $lte: end }
    });

    const payments = await Payment.find({
      date: { $gte: start, $lte: end }
    });

    const doc = new PDFDocument({
  margin: 50,
  userPassword: process.env.PDF_USER_PASSWORD,
  ownerPassword: process.env.PDF_OWNER_PASSWORD,
  permissions: {
    printing: "highResolution",
    modifying: false,
    copying: false
  }
});

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=Monthly_Report_${month}.pdf`
    );

    doc.pipe(res);

    doc.fontSize(22).text("VS UNISEX SALON", { align: "center" });
    doc.moveDown();

    doc.fontSize(16).text("Monthly Business Report", { align: "center" });
    doc.moveDown();

    doc.text(`Month: ${month}`, { align: "center" });

    doc.moveDown(2);

    /* Appointments */

    doc.fontSize(16).text("Appointments", { underline: true });

    appointments.forEach((a, i) => {
      doc
        .fontSize(12)
        .text(`${i + 1}. ${a.service} | ${a.time} | ${a.stylist} | ${a.date}`);
    });

    doc.moveDown();

    /* Payments */

    doc.fontSize(16).text("Payments", { underline: true });

    let total = 0;
    let cash = 0;
    let upi = 0;

    payments.forEach((p, i) => {
      doc.text(`${i + 1}. ${p.method} - ₹${p.amount} - ${p.date}`);

      total += Number(p.amount);

      if (p.method === "Cash") cash += Number(p.amount);
      if (p.method === "UPI") upi += Number(p.amount);
    });

    doc.moveDown();

    doc.fontSize(16).text("Monthly Summary", { underline: true });

    doc.text(`Total Cash : ₹${cash}`);
    doc.text(`Total UPI : ₹${upi}`);
    doc.text(`Total Monthly Income : ₹${total}`);

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("gray")
      .text("Generated by VS Salon Management System", {
        align: "center"
      });

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Monthly PDF failed" });
  }
};